# Generated by Django 3.1.7 on 2021-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_actve', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='phone number')),
                ('insta', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='instagram handle')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('match_radius', models.CharField(blank=True, max_length=30, null=True)),
                ('age_range', models.CharField(blank=True, max_length=7, null=True, verbose_name='age preference')),
                ('gender_preference', models.CharField(blank=True, max_length=15, null=True)),
                ('top_tracks_ids', models.CharField(max_length=50)),
                ('top_tracks_names', models.CharField(max_length=50)),
                ('top_artist_ids', models.CharField(max_length=100)),
                ('top_artist_names', models.CharField(max_length=100)),
                ('time_frame', models.DurationField(blank=True, null=True)),
                ('spotify_token', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('response_type', models.CharField(max_length=50)),
                ('redirect_uri', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('scopes', models.CharField(max_length=100)),
                ('grant_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
