# Generated by Django 3.1.7 on 2021-03-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='high_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='highest age'),
        ),
        migrations.AddField(
            model_name='account',
            name='low_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='lowest age'),
        ),
    ]
