# Generated by Django 3.1.7 on 2021-03-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20210329_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
